/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as CartRouteImport } from './routes/cart'
import { Route as DesignSystemRouteImport } from './routes/design-system'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as AccountIndexRouteImport } from './routes/account.index'
import { Route as AccountInboxRouteImport } from './routes/account.inbox'
import { Route as CategoriesIndexRouteImport } from './routes/categories.index'
import { Route as CategoriesSlugRouteImport } from './routes/categories.$slug'
import { Route as ProductsSlugRouteImport } from './routes/products.$slug'
import { Route as AccountAddressesIndexRouteImport } from './routes/account.addresses.index'
import { Route as AccountAddressesIdRouteImport } from './routes/account.addresses.$id'
import { Route as AccountAddressesNewRouteImport } from './routes/account.addresses.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignSystemRoute = DesignSystemRouteImport.update({
  id: '/design-system',
  path: '/design-system',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountRoute,
} as any)
const AccountInboxRoute = AccountInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AccountRoute,
} as any)
const CategoriesIndexRoute = CategoriesIndexRouteImport.update({
  id: '/categories/',
  path: '/categories/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesSlugRoute = CategoriesSlugRouteImport.update({
  id: '/categories/$slug',
  path: '/categories/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountAddressesIndexRoute = AccountAddressesIndexRouteImport.update({
  id: '/addresses/',
  path: '/addresses/',
  getParentRoute: () => AccountRoute,
} as any)
const AccountAddressesIdRoute = AccountAddressesIdRouteImport.update({
  id: '/addresses/$id',
  path: '/addresses/$id',
  getParentRoute: () => AccountRoute,
} as any)
const AccountAddressesNewRoute = AccountAddressesNewRouteImport.update({
  id: '/addresses/new',
  path: '/addresses/new',
  getParentRoute: () => AccountRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/cart': typeof CartRoute
  '/design-system': typeof DesignSystemRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/search': typeof SearchRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/account/inbox': typeof AccountInboxRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/account/': typeof AccountIndexRoute
  '/categories/': typeof CategoriesIndexRoute
  '/account/addresses/$id': typeof AccountAddressesIdRoute
  '/account/addresses/new': typeof AccountAddressesNewRoute
  '/account/addresses/': typeof AccountAddressesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/design-system': typeof DesignSystemRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/search': typeof SearchRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/account/inbox': typeof AccountInboxRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/account': typeof AccountIndexRoute
  '/categories': typeof CategoriesIndexRoute
  '/account/addresses/$id': typeof AccountAddressesIdRoute
  '/account/addresses/new': typeof AccountAddressesNewRoute
  '/account/addresses': typeof AccountAddressesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/cart': typeof CartRoute
  '/design-system': typeof DesignSystemRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/search': typeof SearchRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/account/inbox': typeof AccountInboxRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/account/': typeof AccountIndexRoute
  '/categories/': typeof CategoriesIndexRoute
  '/account/addresses/$id': typeof AccountAddressesIdRoute
  '/account/addresses/new': typeof AccountAddressesNewRoute
  '/account/addresses/': typeof AccountAddressesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/cart'
    | '/design-system'
    | '/forgot-password'
    | '/search'
    | '/sign-in'
    | '/sign-up'
    | '/account/inbox'
    | '/categories/$slug'
    | '/products/$slug'
    | '/account/'
    | '/categories/'
    | '/account/addresses/$id'
    | '/account/addresses/new'
    | '/account/addresses/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/design-system'
    | '/forgot-password'
    | '/search'
    | '/sign-in'
    | '/sign-up'
    | '/account/inbox'
    | '/categories/$slug'
    | '/products/$slug'
    | '/account'
    | '/categories'
    | '/account/addresses/$id'
    | '/account/addresses/new'
    | '/account/addresses'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/cart'
    | '/design-system'
    | '/forgot-password'
    | '/search'
    | '/sign-in'
    | '/sign-up'
    | '/account/inbox'
    | '/categories/$slug'
    | '/products/$slug'
    | '/account/'
    | '/categories/'
    | '/account/addresses/$id'
    | '/account/addresses/new'
    | '/account/addresses/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRouteWithChildren
  CartRoute: typeof CartRoute
  DesignSystemRoute: typeof DesignSystemRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  SearchRoute: typeof SearchRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  CategoriesSlugRoute: typeof CategoriesSlugRoute
  ProductsSlugRoute: typeof ProductsSlugRoute
  CategoriesIndexRoute: typeof CategoriesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design-system': {
      id: '/design-system'
      path: '/design-system'
      fullPath: '/design-system'
      preLoaderRoute: typeof DesignSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/inbox': {
      id: '/account/inbox'
      path: '/inbox'
      fullPath: '/account/inbox'
      preLoaderRoute: typeof AccountInboxRouteImport
      parentRoute: typeof AccountRoute
    }
    '/categories/': {
      id: '/categories/'
      path: '/categories'
      fullPath: '/categories/'
      preLoaderRoute: typeof CategoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/$slug': {
      id: '/categories/$slug'
      path: '/categories/$slug'
      fullPath: '/categories/$slug'
      preLoaderRoute: typeof CategoriesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/addresses/': {
      id: '/account/addresses/'
      path: '/addresses'
      fullPath: '/account/addresses/'
      preLoaderRoute: typeof AccountAddressesIndexRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/addresses/$id': {
      id: '/account/addresses/$id'
      path: '/addresses/$id'
      fullPath: '/account/addresses/$id'
      preLoaderRoute: typeof AccountAddressesIdRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/addresses/new': {
      id: '/account/addresses/new'
      path: '/addresses/new'
      fullPath: '/account/addresses/new'
      preLoaderRoute: typeof AccountAddressesNewRouteImport
      parentRoute: typeof AccountRoute
    }
  }
}

interface AccountRouteChildren {
  AccountInboxRoute: typeof AccountInboxRoute
  AccountIndexRoute: typeof AccountIndexRoute
  AccountAddressesIdRoute: typeof AccountAddressesIdRoute
  AccountAddressesNewRoute: typeof AccountAddressesNewRoute
  AccountAddressesIndexRoute: typeof AccountAddressesIndexRoute
}

const AccountRouteChildren: AccountRouteChildren = {
  AccountInboxRoute: AccountInboxRoute,
  AccountIndexRoute: AccountIndexRoute,
  AccountAddressesIdRoute: AccountAddressesIdRoute,
  AccountAddressesNewRoute: AccountAddressesNewRoute,
  AccountAddressesIndexRoute: AccountAddressesIndexRoute,
}

const AccountRouteWithChildren =
  AccountRoute._addFileChildren(AccountRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRouteWithChildren,
  CartRoute: CartRoute,
  DesignSystemRoute: DesignSystemRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  SearchRoute: SearchRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  CategoriesSlugRoute: CategoriesSlugRoute,
  ProductsSlugRoute: ProductsSlugRoute,
  CategoriesIndexRoute: CategoriesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
