/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as CartRouteImport } from './routes/cart'
import { Route as DealsRouteImport } from './routes/deals'
import { Route as DesignSystemRouteImport } from './routes/design-system'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as HelpRouteImport } from './routes/help'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as AccountIndexRouteImport } from './routes/account.index'
import { Route as AccountDevicesRouteImport } from './routes/account.devices'
import { Route as AccountInboxRouteImport } from './routes/account.inbox'
import { Route as AccountProfileRouteImport } from './routes/account.profile'
import { Route as AccountReturnsRouteImport } from './routes/account.returns'
import { Route as AccountReviewsRouteImport } from './routes/account.reviews'
import { Route as AccountWatchRouteImport } from './routes/account.watch'
import { Route as AccountWishlistRouteImport } from './routes/account.wishlist'
import { Route as CategoriesIndexRouteImport } from './routes/categories.index'
import { Route as CategoriesSlugRouteImport } from './routes/categories.$slug'
import { Route as CheckoutIndexRouteImport } from './routes/checkout.index'
import { Route as CompareCategoryRouteImport } from './routes/compare.$category'
import { Route as FinderIdRouteImport } from './routes/finder.$id'
import { Route as ProductsSlugRouteImport } from './routes/products.$slug'
import { Route as AccountAddressesIndexRouteImport } from './routes/account.addresses.index'
import { Route as AccountAddressesIdRouteImport } from './routes/account.addresses.$id'
import { Route as AccountAddressesNewRouteImport } from './routes/account.addresses.new'
import { Route as AccountOrdersIndexRouteImport } from './routes/account.orders.index'
import { Route as AccountOrdersOrderIdRouteImport } from './routes/account.orders.$orderId'
import { Route as CheckoutOrderIdDoneRouteImport } from './routes/checkout.$orderId.done'
import { Route as CheckoutOrderIdPayRouteImport } from './routes/checkout.$orderId.pay'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const DealsRoute = DealsRouteImport.update({
  id: '/deals',
  path: '/deals',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignSystemRoute = DesignSystemRouteImport.update({
  id: '/design-system',
  path: '/design-system',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountRoute,
} as any)
const AccountDevicesRoute = AccountDevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => AccountRoute,
} as any)
const AccountInboxRoute = AccountInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AccountRoute,
} as any)
const AccountProfileRoute = AccountProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AccountRoute,
} as any)
const AccountReturnsRoute = AccountReturnsRouteImport.update({
  id: '/returns',
  path: '/returns',
  getParentRoute: () => AccountRoute,
} as any)
const AccountReviewsRoute = AccountReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AccountRoute,
} as any)
const AccountWatchRoute = AccountWatchRouteImport.update({
  id: '/watch',
  path: '/watch',
  getParentRoute: () => AccountRoute,
} as any)
const AccountWishlistRoute = AccountWishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => AccountRoute,
} as any)
const CategoriesIndexRoute = CategoriesIndexRouteImport.update({
  id: '/categories/',
  path: '/categories/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesSlugRoute = CategoriesSlugRouteImport.update({
  id: '/categories/$slug',
  path: '/categories/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutIndexRoute = CheckoutIndexRouteImport.update({
  id: '/checkout/',
  path: '/checkout/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareCategoryRoute = CompareCategoryRouteImport.update({
  id: '/compare/$category',
  path: '/compare/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const FinderIdRoute = FinderIdRouteImport.update({
  id: '/finder/$id',
  path: '/finder/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountAddressesIndexRoute = AccountAddressesIndexRouteImport.update({
  id: '/addresses/',
  path: '/addresses/',
  getParentRoute: () => AccountRoute,
} as any)
const AccountAddressesIdRoute = AccountAddressesIdRouteImport.update({
  id: '/addresses/$id',
  path: '/addresses/$id',
  getParentRoute: () => AccountRoute,
} as any)
const AccountAddressesNewRoute = AccountAddressesNewRouteImport.update({
  id: '/addresses/new',
  path: '/addresses/new',
  getParentRoute: () => AccountRoute,
} as any)
const AccountOrdersIndexRoute = AccountOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => AccountRoute,
} as any)
const AccountOrdersOrderIdRoute = AccountOrdersOrderIdRouteImport.update({
  id: '/orders/$orderId',
  path: '/orders/$orderId',
  getParentRoute: () => AccountRoute,
} as any)
const CheckoutOrderIdDoneRoute = CheckoutOrderIdDoneRouteImport.update({
  id: '/checkout/$orderId/done',
  path: '/checkout/$orderId/done',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutOrderIdPayRoute = CheckoutOrderIdPayRouteImport.update({
  id: '/checkout/$orderId/pay',
  path: '/checkout/$orderId/pay',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/cart': typeof CartRoute
  '/deals': typeof DealsRoute
  '/design-system': typeof DesignSystemRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/search': typeof SearchRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/account/devices': typeof AccountDevicesRoute
  '/account/inbox': typeof AccountInboxRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/returns': typeof AccountReturnsRoute
  '/account/reviews': typeof AccountReviewsRoute
  '/account/watch': typeof AccountWatchRoute
  '/account/wishlist': typeof AccountWishlistRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/compare/$category': typeof CompareCategoryRoute
  '/finder/$id': typeof FinderIdRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/account/': typeof AccountIndexRoute
  '/categories/': typeof CategoriesIndexRoute
  '/checkout/': typeof CheckoutIndexRoute
  '/account/addresses/$id': typeof AccountAddressesIdRoute
  '/account/addresses/new': typeof AccountAddressesNewRoute
  '/account/orders/$orderId': typeof AccountOrdersOrderIdRoute
  '/checkout/$orderId/done': typeof CheckoutOrderIdDoneRoute
  '/checkout/$orderId/pay': typeof CheckoutOrderIdPayRoute
  '/account/addresses/': typeof AccountAddressesIndexRoute
  '/account/orders/': typeof AccountOrdersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/deals': typeof DealsRoute
  '/design-system': typeof DesignSystemRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/search': typeof SearchRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/account/devices': typeof AccountDevicesRoute
  '/account/inbox': typeof AccountInboxRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/returns': typeof AccountReturnsRoute
  '/account/reviews': typeof AccountReviewsRoute
  '/account/watch': typeof AccountWatchRoute
  '/account/wishlist': typeof AccountWishlistRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/compare/$category': typeof CompareCategoryRoute
  '/finder/$id': typeof FinderIdRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/account': typeof AccountIndexRoute
  '/categories': typeof CategoriesIndexRoute
  '/checkout': typeof CheckoutIndexRoute
  '/account/addresses/$id': typeof AccountAddressesIdRoute
  '/account/addresses/new': typeof AccountAddressesNewRoute
  '/account/orders/$orderId': typeof AccountOrdersOrderIdRoute
  '/checkout/$orderId/done': typeof CheckoutOrderIdDoneRoute
  '/checkout/$orderId/pay': typeof CheckoutOrderIdPayRoute
  '/account/addresses': typeof AccountAddressesIndexRoute
  '/account/orders': typeof AccountOrdersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/cart': typeof CartRoute
  '/deals': typeof DealsRoute
  '/design-system': typeof DesignSystemRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/search': typeof SearchRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/account/devices': typeof AccountDevicesRoute
  '/account/inbox': typeof AccountInboxRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/returns': typeof AccountReturnsRoute
  '/account/reviews': typeof AccountReviewsRoute
  '/account/watch': typeof AccountWatchRoute
  '/account/wishlist': typeof AccountWishlistRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/compare/$category': typeof CompareCategoryRoute
  '/finder/$id': typeof FinderIdRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/account/': typeof AccountIndexRoute
  '/categories/': typeof CategoriesIndexRoute
  '/checkout/': typeof CheckoutIndexRoute
  '/account/addresses/$id': typeof AccountAddressesIdRoute
  '/account/addresses/new': typeof AccountAddressesNewRoute
  '/account/orders/$orderId': typeof AccountOrdersOrderIdRoute
  '/checkout/$orderId/done': typeof CheckoutOrderIdDoneRoute
  '/checkout/$orderId/pay': typeof CheckoutOrderIdPayRoute
  '/account/addresses/': typeof AccountAddressesIndexRoute
  '/account/orders/': typeof AccountOrdersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/cart'
    | '/deals'
    | '/design-system'
    | '/forgot-password'
    | '/help'
    | '/search'
    | '/sign-in'
    | '/sign-up'
    | '/account/devices'
    | '/account/inbox'
    | '/account/profile'
    | '/account/returns'
    | '/account/reviews'
    | '/account/watch'
    | '/account/wishlist'
    | '/categories/$slug'
    | '/compare/$category'
    | '/finder/$id'
    | '/products/$slug'
    | '/account/'
    | '/categories/'
    | '/checkout/'
    | '/account/addresses/$id'
    | '/account/addresses/new'
    | '/account/orders/$orderId'
    | '/checkout/$orderId/done'
    | '/checkout/$orderId/pay'
    | '/account/addresses/'
    | '/account/orders/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/deals'
    | '/design-system'
    | '/forgot-password'
    | '/help'
    | '/search'
    | '/sign-in'
    | '/sign-up'
    | '/account/devices'
    | '/account/inbox'
    | '/account/profile'
    | '/account/returns'
    | '/account/reviews'
    | '/account/watch'
    | '/account/wishlist'
    | '/categories/$slug'
    | '/compare/$category'
    | '/finder/$id'
    | '/products/$slug'
    | '/account'
    | '/categories'
    | '/checkout'
    | '/account/addresses/$id'
    | '/account/addresses/new'
    | '/account/orders/$orderId'
    | '/checkout/$orderId/done'
    | '/checkout/$orderId/pay'
    | '/account/addresses'
    | '/account/orders'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/cart'
    | '/deals'
    | '/design-system'
    | '/forgot-password'
    | '/help'
    | '/search'
    | '/sign-in'
    | '/sign-up'
    | '/account/devices'
    | '/account/inbox'
    | '/account/profile'
    | '/account/returns'
    | '/account/reviews'
    | '/account/watch'
    | '/account/wishlist'
    | '/categories/$slug'
    | '/compare/$category'
    | '/finder/$id'
    | '/products/$slug'
    | '/account/'
    | '/categories/'
    | '/checkout/'
    | '/account/addresses/$id'
    | '/account/addresses/new'
    | '/account/orders/$orderId'
    | '/checkout/$orderId/done'
    | '/checkout/$orderId/pay'
    | '/account/addresses/'
    | '/account/orders/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRouteWithChildren
  CartRoute: typeof CartRoute
  DealsRoute: typeof DealsRoute
  DesignSystemRoute: typeof DesignSystemRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HelpRoute: typeof HelpRoute
  SearchRoute: typeof SearchRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  CategoriesSlugRoute: typeof CategoriesSlugRoute
  CompareCategoryRoute: typeof CompareCategoryRoute
  FinderIdRoute: typeof FinderIdRoute
  ProductsSlugRoute: typeof ProductsSlugRoute
  CategoriesIndexRoute: typeof CategoriesIndexRoute
  CheckoutIndexRoute: typeof CheckoutIndexRoute
  CheckoutOrderIdDoneRoute: typeof CheckoutOrderIdDoneRoute
  CheckoutOrderIdPayRoute: typeof CheckoutOrderIdPayRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deals': {
      id: '/deals'
      path: '/deals'
      fullPath: '/deals'
      preLoaderRoute: typeof DealsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design-system': {
      id: '/design-system'
      path: '/design-system'
      fullPath: '/design-system'
      preLoaderRoute: typeof DesignSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/devices': {
      id: '/account/devices'
      path: '/devices'
      fullPath: '/account/devices'
      preLoaderRoute: typeof AccountDevicesRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/inbox': {
      id: '/account/inbox'
      path: '/inbox'
      fullPath: '/account/inbox'
      preLoaderRoute: typeof AccountInboxRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/profile': {
      id: '/account/profile'
      path: '/profile'
      fullPath: '/account/profile'
      preLoaderRoute: typeof AccountProfileRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/returns': {
      id: '/account/returns'
      path: '/returns'
      fullPath: '/account/returns'
      preLoaderRoute: typeof AccountReturnsRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/reviews': {
      id: '/account/reviews'
      path: '/reviews'
      fullPath: '/account/reviews'
      preLoaderRoute: typeof AccountReviewsRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/watch': {
      id: '/account/watch'
      path: '/watch'
      fullPath: '/account/watch'
      preLoaderRoute: typeof AccountWatchRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/wishlist': {
      id: '/account/wishlist'
      path: '/wishlist'
      fullPath: '/account/wishlist'
      preLoaderRoute: typeof AccountWishlistRouteImport
      parentRoute: typeof AccountRoute
    }
    '/categories/': {
      id: '/categories/'
      path: '/categories'
      fullPath: '/categories/'
      preLoaderRoute: typeof CategoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/$slug': {
      id: '/categories/$slug'
      path: '/categories/$slug'
      fullPath: '/categories/$slug'
      preLoaderRoute: typeof CategoriesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/': {
      id: '/checkout/'
      path: '/checkout'
      fullPath: '/checkout/'
      preLoaderRoute: typeof CheckoutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/$category': {
      id: '/compare/$category'
      path: '/compare/$category'
      fullPath: '/compare/$category'
      preLoaderRoute: typeof CompareCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finder/$id': {
      id: '/finder/$id'
      path: '/finder/$id'
      fullPath: '/finder/$id'
      preLoaderRoute: typeof FinderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/addresses/': {
      id: '/account/addresses/'
      path: '/addresses'
      fullPath: '/account/addresses/'
      preLoaderRoute: typeof AccountAddressesIndexRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/addresses/$id': {
      id: '/account/addresses/$id'
      path: '/addresses/$id'
      fullPath: '/account/addresses/$id'
      preLoaderRoute: typeof AccountAddressesIdRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/addresses/new': {
      id: '/account/addresses/new'
      path: '/addresses/new'
      fullPath: '/account/addresses/new'
      preLoaderRoute: typeof AccountAddressesNewRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/orders/': {
      id: '/account/orders/'
      path: '/orders'
      fullPath: '/account/orders/'
      preLoaderRoute: typeof AccountOrdersIndexRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/orders/$orderId': {
      id: '/account/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/account/orders/$orderId'
      preLoaderRoute: typeof AccountOrdersOrderIdRouteImport
      parentRoute: typeof AccountRoute
    }
    '/checkout/$orderId/done': {
      id: '/checkout/$orderId/done'
      path: '/checkout/$orderId/done'
      fullPath: '/checkout/$orderId/done'
      preLoaderRoute: typeof CheckoutOrderIdDoneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/$orderId/pay': {
      id: '/checkout/$orderId/pay'
      path: '/checkout/$orderId/pay'
      fullPath: '/checkout/$orderId/pay'
      preLoaderRoute: typeof CheckoutOrderIdPayRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AccountRouteChildren {
  AccountDevicesRoute: typeof AccountDevicesRoute
  AccountInboxRoute: typeof AccountInboxRoute
  AccountProfileRoute: typeof AccountProfileRoute
  AccountReturnsRoute: typeof AccountReturnsRoute
  AccountReviewsRoute: typeof AccountReviewsRoute
  AccountWatchRoute: typeof AccountWatchRoute
  AccountWishlistRoute: typeof AccountWishlistRoute
  AccountIndexRoute: typeof AccountIndexRoute
  AccountAddressesIdRoute: typeof AccountAddressesIdRoute
  AccountAddressesNewRoute: typeof AccountAddressesNewRoute
  AccountOrdersOrderIdRoute: typeof AccountOrdersOrderIdRoute
  AccountAddressesIndexRoute: typeof AccountAddressesIndexRoute
  AccountOrdersIndexRoute: typeof AccountOrdersIndexRoute
}

const AccountRouteChildren: AccountRouteChildren = {
  AccountDevicesRoute: AccountDevicesRoute,
  AccountInboxRoute: AccountInboxRoute,
  AccountProfileRoute: AccountProfileRoute,
  AccountReturnsRoute: AccountReturnsRoute,
  AccountReviewsRoute: AccountReviewsRoute,
  AccountWatchRoute: AccountWatchRoute,
  AccountWishlistRoute: AccountWishlistRoute,
  AccountIndexRoute: AccountIndexRoute,
  AccountAddressesIdRoute: AccountAddressesIdRoute,
  AccountAddressesNewRoute: AccountAddressesNewRoute,
  AccountOrdersOrderIdRoute: AccountOrdersOrderIdRoute,
  AccountAddressesIndexRoute: AccountAddressesIndexRoute,
  AccountOrdersIndexRoute: AccountOrdersIndexRoute,
}

const AccountRouteWithChildren =
  AccountRoute._addFileChildren(AccountRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRouteWithChildren,
  CartRoute: CartRoute,
  DealsRoute: DealsRoute,
  DesignSystemRoute: DesignSystemRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HelpRoute: HelpRoute,
  SearchRoute: SearchRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  CategoriesSlugRoute: CategoriesSlugRoute,
  CompareCategoryRoute: CompareCategoryRoute,
  FinderIdRoute: FinderIdRoute,
  ProductsSlugRoute: ProductsSlugRoute,
  CategoriesIndexRoute: CategoriesIndexRoute,
  CheckoutIndexRoute: CheckoutIndexRoute,
  CheckoutOrderIdDoneRoute: CheckoutOrderIdDoneRoute,
  CheckoutOrderIdPayRoute: CheckoutOrderIdPayRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
