import type { FamilyTier, ProductStatus } from '@borneo/shared';

/** Units on hand per warehouse, in `warehouses` order (blr, ggn, bhw). */
export type Stock = [number, number, number];

export type SeedVariant = {
  sku: string;
  options: Record<string, string>;
  /** Rupees; MRP is genuine (D-31). */
  mrp: number;
  price: number;
  stock?: Stock;
  /** Pre-order variants only: units that may be pre-sold (D-65). */
  preorderCap?: number;
};

export type SeedProduct = {
  slug: string;
  name: string;
  category: string;
  line: string;
  modelNumber: string;
  generation: number;
  tier: 'value' | 'upper_mid' | 'premium';
  familyTier: FamilyTier;
  status: ProductStatus;
  attributes: Record<string, unknown>;
  explainer?: string;
  whoFor?: string;
  notFor?: string;
  launchedAt?: string;
  /** Pre-orders: expected dispatch, days after seeding (D-64). */
  dispatchInDays?: [number, number];
  variants: SeedVariant[];
  faqs?: { question: string; answer: string }[];
};

export const DEFAULT_STOCK: Stock = [12, 8, 10];
const NO_STOCK: Stock = [0, 0, 0];

export const lines: { key: string; category: string; name: string }[] = [
  { key: 'pulse', category: 'smartphones', name: 'Borneo Pulse' },
  { key: 'nova', category: 'smartphones', name: 'Borneo Nova' },
  { key: 'apex', category: 'smartphones', name: 'Borneo Apex' },
  { key: 'echo-buds', category: 'audio', name: 'Echo Buds' },
  { key: 'echo-max', category: 'audio', name: 'Echo Max' },
  { key: 'echo-band', category: 'audio', name: 'Echo Band' },
  { key: 'boom', category: 'audio', name: 'Boom' },
  { key: 'fit', category: 'wearables', name: 'Borneo Fit' },
  { key: 'watch', category: 'wearables', name: 'Borneo Watch' },
  { key: 'power', category: 'accessories', name: 'Borneo Power' },
  { key: 'shield', category: 'accessories', name: 'Borneo Shield' },
  { key: 'fit-straps', category: 'accessories', name: 'Borneo Straps' },
  { key: 'care', category: 'accessories', name: 'Borneo Care' },
  { key: 'home', category: 'smart-home', name: 'Borneo Home' },
  { key: 'vista', category: 'tvs', name: 'Borneo Vista' },
  { key: 'sweep', category: 'robot-vacuums', name: 'Borneo Sweep' },
];

const phone = (
  ram: number,
  storage: number,
  colour: string,
  sku: string,
  mrp: number,
  price: number,
  stock?: Stock,
): SeedVariant => ({
  sku,
  options: { colour, storage: `${ram} GB + ${storage} GB` },
  mrp,
  price,
  ...(stock ? { stock } : {}),
});

const colour = (
  c: string,
  sku: string,
  mrp: number,
  price: number,
  stock?: Stock,
): SeedVariant => ({
  sku,
  options: { colour: c },
  mrp,
  price,
  ...(stock ? { stock } : {}),
});

const one = (sku: string, mrp: number, price: number, stock?: Stock): SeedVariant => ({
  sku,
  options: {},
  mrp,
  price,
  ...(stock ? { stock } : {}),
});

const smartphones: SeedProduct[] = [
  {
    slug: 'pulse-3',
    name: 'Borneo Pulse 3',
    category: 'smartphones',
    line: 'pulse',
    modelNumber: 'BP3-2024',
    generation: 3,
    tier: 'value',
    familyTier: 'standard',
    status: 'discontinued',
    launchedAt: '2024-03-12',
    attributes: {
      display_size_in: 6.5,
      refresh_rate_hz: 90,
      chipset: 'Dimensity 6080',
      ram_gb: 6,
      os: 'Android 14, 2 years of updates',
      battery_mah: 5000,
      charging_w: 18,
      main_camera_mp: 50,
      five_g: true,
      nfc: false,
      esim: false,
      connector: 'usb_c',
      ip_rating: 'IP52',
      weight_g: 192,
      case_fit: 'pulse-3',
    },
    explainer: 'The previous Pulse. Replaced by Pulse 4; still supported with security updates.',
    whoFor: 'Existing owners looking for accessories and support.',
    notFor: 'New buyers: Pulse 4 has a 120 Hz screen and charges almost twice as fast.',
    variants: [phone(6, 128, 'Graphite', 'BP3-6-128-GRA', 13999, 11999, NO_STOCK)],
  },
  {
    slug: 'pulse-4',
    name: 'Borneo Pulse 4',
    category: 'smartphones',
    line: 'pulse',
    modelNumber: 'BP4-2025',
    generation: 4,
    tier: 'value',
    familyTier: 'standard',
    status: 'live',
    launchedAt: '2025-08-20',
    attributes: {
      display_size_in: 6.6,
      refresh_rate_hz: 120,
      chipset: 'Dimensity 7025',
      ram_gb: 6,
      os: 'Android 15, 3 years of updates',
      battery_mah: 5500,
      charging_w: 33,
      main_camera_mp: 50,
      five_g: true,
      nfc: true,
      esim: false,
      connector: 'usb_c',
      ip_rating: 'IP54',
      weight_g: 189,
      case_fit: 'pulse-4',
    },
    explainer:
      'A 120 Hz screen and a two-day battery for under ₹20,000. The camera is good in daylight and average at night.',
    whoFor:
      'First smartphone, a reliable second phone, or anyone who mostly messages, streams and pays by UPI.',
    notFor: 'Mobile gaming at high settings or low-light photography.',
    variants: [
      phone(6, 128, 'Forest', 'BP4-6-128-FOR', 16999, 14999),
      phone(6, 128, 'Graphite', 'BP4-6-128-GRA', 16999, 14999),
      phone(8, 256, 'Graphite', 'BP4-8-256-GRA', 18999, 16999, [40, 25, 20]),
    ],
    faqs: [
      {
        question: 'Can I pay by tapping Pulse 4?',
        answer: 'Yes. Pulse 4 has NFC for tap-to-pay.',
      },
      {
        question: 'Does Pulse 4 support eSIM?',
        answer: 'No, it takes a physical SIM. Nova 3 and newer, and every Apex, support eSIM.',
      },
      {
        question: 'How long will Pulse 4 get updates?',
        answer: 'Three years of updates, starting from Android 15.',
      },
    ],
  },
  {
    slug: 'pulse-4-pro',
    name: 'Borneo Pulse 4 Pro',
    category: 'smartphones',
    line: 'pulse',
    modelNumber: 'BP4P-2025',
    generation: 4,
    tier: 'value',
    familyTier: 'pro',
    status: 'live',
    launchedAt: '2025-08-20',
    attributes: {
      display_size_in: 6.7,
      refresh_rate_hz: 120,
      chipset: 'Snapdragon 7s Gen 3',
      ram_gb: 8,
      os: 'Android 15, 3 years of updates',
      battery_mah: 5500,
      charging_w: 67,
      main_camera_mp: 64,
      five_g: true,
      nfc: true,
      esim: false,
      connector: 'usb_c',
      ip_rating: 'IP64',
      weight_g: 194,
      case_fit: 'pulse-4-pro',
    },
    explainer: 'Pulse 4 with a faster chip, 67 W charging and a better main camera.',
    whoFor: 'Casual gamers and anyone who wants a full charge in under 45 minutes.',
    notFor: 'Buyers who need wireless charging or an eSIM.',
    variants: [
      phone(8, 128, 'Ocean', 'BP4P-8-128-OCE', 21999, 19999),
      phone(8, 256, 'Ocean', 'BP4P-8-256-OCE', 23999, 21999),
    ],
  },
  {
    slug: 'nova-2',
    name: 'Borneo Nova 2',
    category: 'smartphones',
    line: 'nova',
    modelNumber: 'BN2-2024',
    generation: 2,
    tier: 'upper_mid',
    familyTier: 'standard',
    status: 'live',
    launchedAt: '2024-09-05',
    attributes: {
      display_size_in: 6.55,
      refresh_rate_hz: 120,
      chipset: 'Snapdragon 7 Gen 1',
      ram_gb: 8,
      os: 'Android 15, updates until 2027',
      battery_mah: 4800,
      charging_w: 45,
      wireless_charging: false,
      main_camera_mp: 50,
      five_g: true,
      nfc: true,
      esim: false,
      connector: 'usb_c',
      ip_rating: 'IP54',
      weight_g: 182,
      case_fit: 'nova-2',
    },
    explainer: 'Last year’s Nova at a lower price. Same AMOLED screen, older chip.',
    whoFor: 'Anyone who wants an AMOLED screen and a slim phone on a tighter budget.',
    notFor: 'Heavy users: the 4,800 mAh battery lasts a day, not two.',
    variants: [phone(8, 128, 'Mist', 'BN2-8-128-MIS', 27999, 21999)],
  },
  {
    slug: 'nova-3',
    name: 'Borneo Nova 3',
    category: 'smartphones',
    line: 'nova',
    modelNumber: 'BN3-2025',
    generation: 3,
    tier: 'upper_mid',
    familyTier: 'standard',
    status: 'live',
    launchedAt: '2025-09-10',
    attributes: {
      display_size_in: 6.6,
      refresh_rate_hz: 120,
      chipset: 'Snapdragon 7+ Gen 3',
      ram_gb: 8,
      os: 'Android 16, 4 years of updates',
      battery_mah: 5200,
      charging_w: 67,
      wireless_charging: true,
      main_camera_mp: 50,
      five_g: true,
      nfc: true,
      esim: true,
      connector: 'usb_c',
      ip_rating: 'IP64',
      weight_g: 185,
      case_fit: 'nova-3',
    },
    explainer:
      'The all-rounder: flagship-class chip, wireless charging and four years of updates, without flagship pricing.',
    whoFor: 'Most people who keep a phone for three years or more.',
    notFor: 'Anyone who needs a telephoto lens; the Pro has one.',
    variants: [
      phone(8, 128, 'Mist', 'BN3-8-128-MIS', 32999, 29999),
      phone(8, 256, 'Midnight', 'BN3-8-256-MID', 34999, 31999),
      phone(12, 256, 'Midnight', 'BN3-12-256-MID', 36999, 33999),
    ],
    faqs: [
      {
        question: 'Does Nova 3 support wireless charging?',
        answer:
          'Yes. It charges on any Qi pad, including the Borneo 15 W pad, and at up to 67 W wired.',
      },
    ],
  },
  {
    slug: 'nova-3-pro',
    name: 'Borneo Nova 3 Pro',
    category: 'smartphones',
    line: 'nova',
    modelNumber: 'BN3P-2025',
    generation: 3,
    tier: 'upper_mid',
    familyTier: 'pro',
    status: 'live',
    launchedAt: '2025-09-10',
    attributes: {
      display_size_in: 6.7,
      refresh_rate_hz: 120,
      chipset: 'Snapdragon 8s Gen 3',
      ram_gb: 12,
      os: 'Android 16, 4 years of updates',
      battery_mah: 5400,
      charging_w: 80,
      wireless_charging: true,
      main_camera_mp: 50,
      five_g: true,
      nfc: true,
      esim: true,
      connector: 'usb_c',
      ip_rating: 'IP68',
      weight_g: 199,
      case_fit: 'nova-3-pro',
    },
    explainer: 'Nova 3 plus a 3× telephoto camera, IP68 and a faster chip.',
    whoFor: 'People who take portraits and zoom shots, or want full water resistance.',
    notFor: 'Small hands: it is the largest Nova.',
    variants: [
      phone(12, 256, 'Sand', 'BN3P-12-256-SAN', 39999, 34999),
      phone(12, 512, 'Midnight', 'BN3P-12-512-MID', 43999, 38999),
    ],
  },
  {
    slug: 'nova-4',
    name: 'Borneo Nova 4',
    category: 'smartphones',
    line: 'nova',
    modelNumber: 'BN4-2026',
    generation: 4,
    tier: 'upper_mid',
    familyTier: 'standard',
    status: 'preorder',
    dispatchInDays: [21, 28],
    attributes: {
      display_size_in: 6.6,
      refresh_rate_hz: 144,
      chipset: 'Snapdragon 7 Gen 4',
      ram_gb: 12,
      os: 'Android 16, 5 years of updates',
      battery_mah: 6000,
      charging_w: 80,
      wireless_charging: true,
      main_camera_mp: 50,
      five_g: true,
      nfc: true,
      esim: true,
      connector: 'usb_c',
      ip_rating: 'IP68',
      weight_g: 188,
      case_fit: 'nova-4',
    },
    explainer:
      'The next Nova: a 6,000 mAh battery in a lighter body and five years of updates. Pay in full now; cancel free before dispatch.',
    whoFor: 'Nova 2 owners and anyone happy to wait a few weeks for the newest model.',
    notFor: 'Anyone who needs a phone this week: Nova 3 ships now.',
    variants: [
      { ...phone(12, 256, 'Glacier', 'BN4-12-256-GLA', 37999, 34999, NO_STOCK), preorderCap: 200 },
    ],
  },
  {
    slug: 'apex-1',
    name: 'Borneo Apex 1',
    category: 'smartphones',
    line: 'apex',
    modelNumber: 'BA1-2024',
    generation: 1,
    tier: 'premium',
    familyTier: 'standard',
    status: 'live',
    launchedAt: '2024-11-01',
    attributes: {
      display_size_in: 6.7,
      refresh_rate_hz: 120,
      chipset: 'Snapdragon 8 Gen 3',
      ram_gb: 12,
      os: 'Android 16, updates until 2029',
      battery_mah: 5000,
      charging_w: 80,
      wireless_charging: true,
      main_camera_mp: 50,
      five_g: true,
      nfc: true,
      esim: true,
      connector: 'usb_c',
      ip_rating: 'IP68',
      weight_g: 205,
      case_fit: 'apex-1',
    },
    explainer: 'The first Apex. Still a flagship camera and screen, now at a lower price.',
    whoFor: 'Flagship features without the newest-model price.',
    notFor: 'Anyone wanting the longest battery life in the range.',
    variants: [phone(12, 256, 'Obsidian', 'BA1-12-256-OBS', 54999, 49999)],
  },
  {
    slug: 'apex-2',
    name: 'Borneo Apex 2',
    category: 'smartphones',
    line: 'apex',
    modelNumber: 'BA2-2025',
    generation: 2,
    tier: 'premium',
    familyTier: 'standard',
    status: 'live',
    launchedAt: '2025-11-05',
    attributes: {
      display_size_in: 6.7,
      refresh_rate_hz: 120,
      chipset: 'Snapdragon 8 Elite',
      ram_gb: 12,
      os: 'Android 16, 6 years of updates',
      battery_mah: 5500,
      charging_w: 90,
      wireless_charging: true,
      main_camera_mp: 50,
      five_g: true,
      nfc: true,
      esim: true,
      connector: 'usb_c',
      ip_rating: 'IP68',
      weight_g: 210,
      case_fit: 'apex-2',
    },
    explainer:
      'Borneo’s flagship: the fastest chip, a 1-inch-type main sensor and six years of updates. The USB-C cable is in the box.',
    whoFor: 'People who shoot a lot of photos and video and keep their phone for years.',
    notFor: 'Anyone who wants a compact phone.',
    variants: [
      phone(12, 256, 'Obsidian', 'BA2-12-256-OBS', 69999, 64999),
      phone(16, 512, 'Titanium', 'BA2-16-512-TIT', 79999, 74999),
    ],
    faqs: [
      {
        question: 'Is a USB-C cable included with Apex 2?',
        answer: 'Yes. The charger is sold separately; Apex 2 takes up to 90 W wired.',
      },
    ],
  },
  {
    slug: 'apex-2-premium',
    name: 'Borneo Apex 2 Premium',
    category: 'smartphones',
    line: 'apex',
    modelNumber: 'BA2X-2025',
    generation: 2,
    tier: 'premium',
    familyTier: 'premium',
    status: 'live',
    launchedAt: '2025-11-05',
    attributes: {
      display_size_in: 6.8,
      refresh_rate_hz: 120,
      chipset: 'Snapdragon 8 Elite',
      ram_gb: 16,
      os: 'Android 16, 6 years of updates',
      battery_mah: 5700,
      charging_w: 120,
      wireless_charging: true,
      main_camera_mp: 50,
      five_g: true,
      nfc: true,
      esim: true,
      connector: 'usb_c',
      ip_rating: 'IP68',
      weight_g: 221,
      case_fit: 'apex-2-premium',
    },
    explainer: 'Apex 2 with a 5× periscope camera, a titanium frame and 120 W charging.',
    whoFor: 'Travel and wildlife photographers, and anyone who wants the best Borneo makes.',
    notFor: 'Light users: Apex 2 covers almost everything for less.',
    variants: [phone(16, 1024, 'Titanium', 'BA2X-16-1T-TIT', 94999, 89999, [6, 4, 4])],
  },
];

const audio: SeedProduct[] = [
  {
    slug: 'echo-buds-1',
    name: 'Echo Buds 1',
    category: 'audio',
    line: 'echo-buds',
    modelNumber: 'EB1-2024',
    generation: 1,
    tier: 'value',
    familyTier: 'standard',
    status: 'live',
    launchedAt: '2024-02-14',
    attributes: {
      form_factor: 'tws',
      anc: false,
      playback_hours: 6,
      case_hours: 24,
      bluetooth_version: 5.2,
      codecs: ['SBC', 'AAC'],
      multipoint: false,
      works_with_android: true,
      works_with_iphone: true,
      water_resistance: 'IPX4',
      driver_mm: 10,
      connector: 'usb_c',
      weight_g: 4.5,
      tip_fit: 'echo-tips-v1',
    },
    explainer: 'Simple, light earbuds for calls and commutes. No noise cancellation.',
    whoFor: 'A first pair of wireless earbuds or a spare for the gym.',
    notFor: 'Flights and noisy offices.',
    variants: [colour('White', 'EB1-WHT', 3999, 2499), colour('Black', 'EB1-BLK', 3999, 2499)],
  },
  {
    slug: 'echo-buds-2',
    name: 'Echo Buds 2',
    category: 'audio',
    line: 'echo-buds',
    modelNumber: 'EB2-2025',
    generation: 2,
    tier: 'value',
    familyTier: 'standard',
    status: 'live',
    launchedAt: '2025-06-01',
    attributes: {
      form_factor: 'tws',
      anc: true,
      playback_hours: 8,
      case_hours: 36,
      bluetooth_version: 5.3,
      codecs: ['SBC', 'AAC'],
      multipoint: true,
      works_with_android: true,
      works_with_iphone: true,
      water_resistance: 'IPX5',
      driver_mm: 11,
      connector: 'usb_c',
      weight_g: 4.8,
      tip_fit: 'echo-tips-v2',
    },
    explainer:
      'Noise cancellation that handles traffic and fans well, and multipoint so they switch between phone and laptop.',
    whoFor: 'Daily commuters and people who move between calls on two devices.',
    notFor: 'Audiophiles who want LDAC hi-res audio.',
    variants: [
      colour('Black', 'EB2-BLK', 4999, 3499, [30, 20, 20]),
      colour('Sage', 'EB2-SGE', 4999, 3499),
    ],
    faqs: [
      {
        question: 'Can Echo Buds 2 connect to two devices at once?',
        answer:
          'Yes. Multipoint keeps them paired to two devices and switches to whichever plays audio.',
      },
    ],
  },
  {
    slug: 'echo-buds-2-pro',
    name: 'Echo Buds 2 Pro',
    category: 'audio',
    line: 'echo-buds',
    modelNumber: 'EB2P-2025',
    generation: 2,
    tier: 'upper_mid',
    familyTier: 'pro',
    status: 'live',
    launchedAt: '2025-06-01',
    attributes: {
      form_factor: 'tws',
      anc: true,
      playback_hours: 9,
      case_hours: 40,
      bluetooth_version: 5.4,
      codecs: ['SBC', 'AAC', 'LDAC'],
      multipoint: true,
      works_with_android: true,
      works_with_iphone: true,
      water_resistance: 'IP55',
      driver_mm: 11,
      connector: 'usb_c',
      weight_g: 5.1,
      tip_fit: 'echo-tips-v2',
    },
    explainer:
      'Echo Buds 2 with stronger noise cancellation, LDAC hi-res audio and wireless charging.',
    whoFor: 'Frequent flyers and anyone with a phone that supports LDAC.',
    notFor: 'iPhone users chasing hi-res: iPhone does not support LDAC.',
    variants: [colour('Graphite', 'EB2P-GRA', 7999, 5999)],
  },
  {
    slug: 'echo-max-1',
    name: 'Echo Max 1',
    category: 'audio',
    line: 'echo-max',
    modelNumber: 'EM1-2024',
    generation: 1,
    tier: 'upper_mid',
    familyTier: 'standard',
    status: 'live',
    launchedAt: '2024-10-10',
    attributes: {
      form_factor: 'over_ear',
      anc: true,
      playback_hours: 40,
      bluetooth_version: 5.2,
      codecs: ['SBC', 'AAC'],
      multipoint: true,
      works_with_android: true,
      works_with_iphone: true,
      driver_mm: 40,
      connector: 'usb_c',
      weight_g: 265,
    },
    explainer: 'Comfortable over-ear headphones with 40 hours of battery.',
    whoFor: 'Long work-from-home days and train journeys.',
    notFor: 'Workouts: they are not sweat resistant.',
    variants: [colour('Black', 'EM1-BLK', 9999, 7999)],
  },
  {
    slug: 'echo-max-2',
    name: 'Echo Max 2',
    category: 'audio',
    line: 'echo-max',
    modelNumber: 'EM2-2026',
    generation: 2,
    tier: 'premium',
    familyTier: 'standard',
    status: 'live',
    launchedAt: '2026-04-15',
    attributes: {
      form_factor: 'over_ear',
      anc: true,
      playback_hours: 50,
      bluetooth_version: 5.4,
      codecs: ['SBC', 'AAC', 'LDAC', 'LC3'],
      multipoint: true,
      works_with_android: true,
      works_with_iphone: true,
      driver_mm: 40,
      connector: 'usb_c',
      weight_g: 250,
    },
    explainer:
      'Borneo’s best noise cancellation, lighter than Max 1, with LDAC and 50 hours of battery.',
    whoFor: 'Frequent flyers and people who listen for hours every day.',
    notFor: 'Anyone who wants headphones that fold small.',
    variants: [colour('Black', 'EM2-BLK', 14999, 12999), colour('Stone', 'EM2-STN', 14999, 12999)],
  },
  {
    slug: 'echo-band-1',
    name: 'Echo Band 1',
    category: 'audio',
    line: 'echo-band',
    modelNumber: 'EBN1-2025',
    generation: 1,
    tier: 'value',
    familyTier: 'standard',
    status: 'live',
    launchedAt: '2025-01-20',
    attributes: {
      form_factor: 'neckband',
      anc: false,
      playback_hours: 30,
      bluetooth_version: 5.3,
      codecs: ['SBC', 'AAC'],
      multipoint: true,
      works_with_android: true,
      works_with_iphone: true,
      water_resistance: 'IPX5',
      driver_mm: 12,
      connector: 'usb_c',
      weight_g: 28,
    },
    explainer: 'A neckband that lasts 30 hours and gets 10 hours from a 10-minute charge.',
    whoFor: 'People who keep losing earbuds, runners, and long call days.',
    notFor: 'Anyone who wants noise cancellation.',
    variants: [one('EBN1-BLK', 1999, 1499)],
  },
  {
    slug: 'boom-mini',
    name: 'Boom Mini',
    category: 'audio',
    line: 'boom',
    modelNumber: 'BM1-2024',
    generation: 1,
    tier: 'value',
    familyTier: 'standard',
    status: 'live',
    launchedAt: '2024-05-01',
    attributes: {
      form_factor: 'speaker',
      playback_hours: 12,
      bluetooth_version: 5.3,
      codecs: ['SBC'],
      works_with_android: true,
      works_with_iphone: true,
      water_resistance: 'IP67',
      connector: 'usb_c',
      weight_g: 260,
    },
    explainer: 'A pocketable waterproof speaker.',
    whoFor: 'Picnics, showers and small rooms.',
    notFor: 'Parties: Boom 2 is much louder.',
    variants: [colour('Coral', 'BM1-COR', 2499, 1999, NO_STOCK)],
  },
  {
    slug: 'boom-2',
    name: 'Boom 2',
    category: 'audio',
    line: 'boom',
    modelNumber: 'BM2-2025',
    generation: 2,
    tier: 'value',
    familyTier: 'standard',
    status: 'live',
    launchedAt: '2025-03-15',
    attributes: {
      form_factor: 'speaker',
      playback_hours: 20,
      bluetooth_version: 5.3,
      codecs: ['SBC', 'AAC'],
      multipoint: true,
      works_with_android: true,
      works_with_iphone: true,
      water_resistance: 'IP67',
      connector: 'usb_c',
      weight_g: 640,
    },
    explainer: 'A loud, waterproof speaker with 20 hours of battery and a strap.',
    whoFor: 'Terrace parties, treks and the beach.',
    notFor: 'Home theatre: it is a portable speaker.',
    variants: [colour('Black', 'BM2-BLK', 5999, 4999)],
  },
];

const wearables: SeedProduct[] = [
  {
    slug: 'fit-band-2',
    name: 'Borneo Fit Band 2',
    category: 'wearables',
    line: 'fit',
    modelNumber: 'FB2-2025',
    generation: 2,
    tier: 'value',
    familyTier: 'standard',
    status: 'live',
    attributes: {
      form_factor: 'band',
      display_size_in: 1.47,
      battery_days: 14,
      gps: false,
      calling: false,
      works_with_android: true,
      works_with_iphone: true,
      strap_width_mm: 18,
      water_resistance: '5ATM',
    },
    variants: [colour('Black', 'FB2-BLK', 3999, 2999)],
  },
  {
    slug: 'watch-s1',
    name: 'Borneo Watch S1',
    category: 'wearables',
    line: 'watch',
    modelNumber: 'WS1-2024',
    generation: 1,
    tier: 'upper_mid',
    familyTier: 'standard',
    status: 'live',
    attributes: {
      form_factor: 'watch',
      display_size_in: 1.43,
      battery_days: 7,
      gps: false,
      calling: true,
      works_with_android: true,
      works_with_iphone: true,
      strap_width_mm: 20,
      water_resistance: 'IP68',
    },
    variants: [colour('Black', 'WS1-BLK', 7999, 5999)],
  },
  {
    slug: 'watch-s2',
    name: 'Borneo Watch S2',
    category: 'wearables',
    line: 'watch',
    modelNumber: 'WS2-2025',
    generation: 2,
    tier: 'upper_mid',
    familyTier: 'standard',
    status: 'live',
    attributes: {
      form_factor: 'watch',
      display_size_in: 1.43,
      battery_days: 10,
      gps: true,
      calling: true,
      works_with_android: true,
      works_with_iphone: true,
      strap_width_mm: 20,
      water_resistance: '5ATM',
    },
    variants: [colour('Black', 'WS2-BLK', 10999, 9999), colour('Silver', 'WS2-SLV', 10999, 9999)],
  },
  {
    slug: 'watch-s2-pro',
    name: 'Borneo Watch S2 Pro',
    category: 'wearables',
    line: 'watch',
    modelNumber: 'WS2P-2025',
    generation: 2,
    tier: 'premium',
    familyTier: 'pro',
    status: 'live',
    attributes: {
      form_factor: 'watch',
      display_size_in: 1.5,
      battery_days: 14,
      gps: true,
      calling: true,
      works_with_android: true,
      works_with_iphone: true,
      strap_width_mm: 22,
      water_resistance: '5ATM',
    },
    variants: [colour('Titanium', 'WS2P-TIT', 15999, 13999)],
  },
];

const accessory = (
  slug: string,
  name: string,
  line: string,
  modelNumber: string,
  attributes: Record<string, unknown>,
  mrp: number,
  price: number,
): SeedProduct => ({
  slug,
  name,
  category: 'accessories',
  line,
  modelNumber,
  generation: 1,
  tier: 'value',
  familyTier: 'standard',
  status: 'live',
  attributes,
  variants: [one(modelNumber, mrp, price, [50, 40, 40])],
});

const accessories: SeedProduct[] = [
  accessory(
    'charger-33w',
    'Borneo 33 W USB-C charger',
    'power',
    'PWR-33',
    { accessory_type: 'charger', connector: 'usb_c', output_w: 33 },
    1299,
    999,
  ),
  accessory(
    'charger-67w-gan',
    'Borneo 67 W GaN charger',
    'power',
    'PWR-67G',
    { accessory_type: 'charger', connector: 'usb_c', output_w: 67 },
    2499,
    1999,
  ),
  accessory(
    'cable-usb-c-1m',
    'Borneo USB-C cable, 1 m',
    'power',
    'CBL-C1',
    { accessory_type: 'cable', connector: 'usb_c', cable_length_m: 1 },
    499,
    399,
  ),
  accessory(
    'cable-usb-c-2m',
    'Borneo USB-C cable, 2 m',
    'power',
    'CBL-C2',
    { accessory_type: 'cable', connector: 'usb_c', cable_length_m: 2 },
    699,
    549,
  ),
  accessory(
    'wireless-pad-15w',
    'Borneo 15 W wireless charging pad',
    'power',
    'PWR-Q15',
    { accessory_type: 'wireless_charger', qi: true, output_w: 15 },
    1999,
    1499,
  ),
  accessory(
    'case-pulse-4',
    'Borneo Shield case for Pulse 4',
    'shield',
    'SHD-BP4',
    { accessory_type: 'case', fits_case: ['pulse-4'] },
    799,
    599,
  ),
  accessory(
    'case-nova-3',
    'Borneo Shield case for Nova 3',
    'shield',
    'SHD-BN3',
    { accessory_type: 'case', fits_case: ['nova-3'] },
    999,
    799,
  ),
  accessory(
    'case-apex-2',
    'Borneo Shield case for Apex 2',
    'shield',
    'SHD-BA2',
    { accessory_type: 'case', fits_case: ['apex-2'] },
    1499,
    1299,
  ),
  accessory(
    'glass-apex-2',
    'Borneo Shield glass for Apex 2',
    'shield',
    'SHD-BA2-G',
    { accessory_type: 'screen_protector', fits_case: ['apex-2', 'apex-2-premium'] },
    899,
    699,
  ),
  accessory(
    'tips-echo-v2',
    'Echo ear tips, 3 sizes',
    'care',
    'TIP-EV2',
    { accessory_type: 'ear_tips', fits_tips: ['echo-tips-v2'] },
    399,
    299,
  ),
  accessory(
    'strap-20mm',
    'Borneo sport strap, 20 mm',
    'fit-straps',
    'STR-20',
    { accessory_type: 'strap', strap_width_mm: 20 },
    999,
    799,
  ),
  accessory(
    'strap-22mm',
    'Borneo sport strap, 22 mm',
    'fit-straps',
    'STR-22',
    { accessory_type: 'strap', strap_width_mm: 22 },
    1099,
    899,
  ),
  accessory(
    'sweep-care-kit',
    'Borneo Sweep care kit',
    'care',
    'CARE-SW',
    { accessory_type: 'vacuum_kit', fits_vacuum: ['sweep-r1', 'sweep-r2'] },
    1599,
    1299,
  ),
];

const home = (
  slug: string,
  name: string,
  modelNumber: string,
  attributes: Record<string, unknown>,
  mrp: number,
  price: number,
  faqs?: SeedProduct['faqs'],
): SeedProduct => ({
  slug,
  name,
  category: 'smart-home',
  line: 'home',
  modelNumber,
  generation: 1,
  tier: 'value',
  familyTier: 'standard',
  status: 'live',
  attributes,
  variants: [one(modelNumber, mrp, price)],
  ...(faqs ? { faqs } : {}),
});

const smartHome: SeedProduct[] = [
  home(
    'smart-plug-16a',
    'Borneo Smart Plug 16 A',
    'HM-PLG16',
    {
      device_type: 'plug',
      works_with_alexa: true,
      works_with_google: true,
      wifi_band: '2.4 GHz',
      needs_hub: false,
      max_load_w: 3500,
    },
    1499,
    1199,
  ),
  home(
    'smart-bulb-9w',
    'Borneo Smart Bulb 9 W',
    'HM-BLB9',
    {
      device_type: 'bulb',
      works_with_alexa: true,
      works_with_google: true,
      wifi_band: '2.4 GHz',
      needs_hub: false,
    },
    899,
    699,
  ),
  home(
    'home-hub-1',
    'Borneo Home Hub',
    'HM-HUB1',
    { device_type: 'hub', works_with_alexa: true, works_with_google: true, wifi_band: 'Dual band' },
    5999,
    4999,
  ),
  home(
    'cam-indoor-2k',
    'Borneo Indoor Camera 2K',
    'HM-CAM2K',
    {
      device_type: 'camera',
      works_with_alexa: true,
      works_with_google: false,
      wifi_band: '2.4 GHz',
      needs_hub: false,
      video_resolution: '2K',
    },
    3999,
    2999,
    [
      {
        question: 'Does the Indoor Camera work with Google Home?',
        answer: 'No. It works with Alexa. The Borneo smart plug and bulb work with both.',
      },
    ],
  ),
];

const tvs: SeedProduct[] = [
  {
    slug: 'vista-43',
    name: 'Borneo Vista 43 4K',
    category: 'tvs',
    line: 'vista',
    modelNumber: 'TV-V43-2025',
    generation: 1,
    tier: 'value',
    familyTier: 'standard',
    status: 'live',
    attributes: {
      screen_size_in: 43,
      resolution: '4K',
      panel: 'LED',
      refresh_rate_hz: 60,
      hdmi_ports: 3,
      dolby_vision: false,
      os: 'Google TV',
      works_with_alexa: false,
      works_with_google: true,
    },
    variants: [one('TV-V43', 32999, 27999, [0, 6, 6])],
  },
  {
    slug: 'vista-55-qled',
    name: 'Borneo Vista 55 QLED',
    category: 'tvs',
    line: 'vista',
    modelNumber: 'TV-V55Q-2025',
    generation: 1,
    tier: 'upper_mid',
    familyTier: 'pro',
    status: 'live',
    attributes: {
      screen_size_in: 55,
      resolution: '4K',
      panel: 'QLED',
      refresh_rate_hz: 120,
      hdmi_ports: 4,
      dolby_vision: true,
      os: 'Google TV',
      works_with_alexa: true,
      works_with_google: true,
    },
    variants: [one('TV-V55Q', 54999, 46999, [0, 4, 4])],
  },
  {
    slug: 'vista-65-oled',
    name: 'Borneo Vista 65 OLED',
    category: 'tvs',
    line: 'vista',
    modelNumber: 'TV-V65O-2025',
    generation: 1,
    tier: 'premium',
    familyTier: 'premium',
    status: 'live',
    attributes: {
      screen_size_in: 65,
      resolution: '4K',
      panel: 'OLED',
      refresh_rate_hz: 120,
      hdmi_ports: 4,
      dolby_vision: true,
      os: 'Google TV',
      works_with_alexa: true,
      works_with_google: true,
    },
    variants: [one('TV-V65O', 159999, 139999, [0, 2, 2])],
  },
];

const robotVacuums: SeedProduct[] = [
  {
    slug: 'sweep-r1',
    name: 'Borneo Sweep R1',
    category: 'robot-vacuums',
    line: 'sweep',
    modelNumber: 'SW-R1-2024',
    generation: 1,
    tier: 'value',
    familyTier: 'standard',
    status: 'live',
    attributes: {
      suction_pa: 2700,
      mop: true,
      self_empty: false,
      runtime_min: 120,
      lidar: false,
      works_with_alexa: true,
      works_with_google: true,
      vacuum_kit_fit: 'sweep-r1',
    },
    variants: [one('SW-R1', 21999, 17999)],
  },
  {
    slug: 'sweep-r2',
    name: 'Borneo Sweep R2',
    category: 'robot-vacuums',
    line: 'sweep',
    modelNumber: 'SW-R2-2025',
    generation: 2,
    tier: 'upper_mid',
    familyTier: 'standard',
    status: 'live',
    attributes: {
      suction_pa: 4000,
      mop: true,
      self_empty: false,
      runtime_min: 150,
      lidar: true,
      works_with_alexa: true,
      works_with_google: true,
      vacuum_kit_fit: 'sweep-r2',
    },
    variants: [one('SW-R2', 29999, 24999)],
  },
  {
    slug: 'sweep-r2-pro',
    name: 'Borneo Sweep R2 Pro',
    category: 'robot-vacuums',
    line: 'sweep',
    modelNumber: 'SW-R2P-2025',
    generation: 2,
    tier: 'premium',
    familyTier: 'pro',
    status: 'live',
    attributes: {
      suction_pa: 6000,
      mop: true,
      self_empty: true,
      runtime_min: 180,
      lidar: true,
      works_with_alexa: true,
      works_with_google: true,
      vacuum_kit_fit: 'sweep-r2',
    },
    variants: [one('SW-R2P', 39999, 34999)],
  },
];

export const products: SeedProduct[] = [
  ...smartphones,
  ...audio,
  ...wearables,
  ...accessories,
  ...smartHome,
  ...tvs,
  ...robotVacuums,
];
